---
title: 'Physicoquemical parameters'
author:
 - Haydé Peruyero (haydeeperuyero@gmail.com)
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r, echo=FALSE, warning=FALSE}
library("phyloseq")
library("ggplot2")
library("RColorBrewer")
library("patchwork")
library("readr")
library("tidyverse")
library("grid")
library("gridExtra")
library("paletteer")
library("forcats")
library(viridis)
library(hrbrthemes)
```





```{r, include=FALSE, message=FALSE, warning=FALSE}
# upload the metadata
df <- read_csv("D:/Users/hayde/Documents/R_sites/honey_diversity/data/metadata_miel.csv")
```

```{r, include=FALSE}
# rename the names of the samples
# change n_specie to specie_n
df <- df %>%
  mutate(SampleID = case_when(
    grepl("_Scapto", ID) ~ paste0("Scapto_", sub("_Scapto.*", "", ID)),
    grepl("_Melli", ID) ~ paste0("Meli_", sub("_Melli.*", "", ID)),
    TRUE ~ as.character(ID) 
  ))
rownames(df) <- df$ID
df$ID <- factor(df$ID, levels = unique(df$ID))
```

```{r, echo=FALSE}
pH <- ggplot(df, aes(x = factor(1),ID , fill= pH)) + 
  geom_tile(color = "white",width = 1, height = 1)+
  #scale_fill_distiller(palette = "YlOrBr")+
  scale_fill_viridis(discrete=FALSE) +
  #scale_fill_thermal(name = "pH") +
  theme_minimal() +
  labs(y = "Samples")+
  theme(legend.text = element_text(size = 12), 
         legend.key.size = unit(0.4, 'cm'), 
         axis.title = element_text(size = 16), 
         axis.text.x = element_blank(),
         axis.ticks.x = element_blank(),
         axis.text.y = element_text(size = 16), 
         plot.title = element_text(size = 20), 
         axis.title.x = element_blank(),
         axis.title.y = element_text(size = 16, face = "bold"), 
         legend.title = element_text(size = 16))+
  coord_fixed(ratio = 1)

pH
```


```{r, eval=FALSE, include=FALSE}
#ggsave(filename = "~/miel/Metagenomics/figures/deep_Scapto.svg", plot = reads, width = 8, height = 5, dpi = 300)

ggsave(filename = "D:/Users/hayde/Documents/R_sites/honey_diversity/figures/heatmap_pH.svg", plot = pH, width = 3, height = 6, dpi = 300)
```


```{r}
ggplot(df, aes(x = factor(1),ID , fill= Moisture)) + 
  geom_tile(color = "white",width = 1, height = 1)+
  scale_fill_viridis(discrete=FALSE) +
  theme_minimal() +
  labs(y = "Samples")+
  theme(legend.text = element_text(size = 12), 
         legend.key.size = unit(0.4, 'cm'), 
         axis.title = element_text(size = 16), 
         axis.text.x = element_blank(),
         axis.ticks.x = element_blank(),
         axis.text.y = element_text(size = 16), 
         plot.title = element_text(size = 20), 
         axis.title.x = element_blank(),
         axis.title.y = element_text(size = 16, face = "bold"), 
         legend.title = element_text(size = 16))+
  coord_fixed(ratio = 1)
```
```{r}
ggplot(df, aes(x = factor(1),ID , fill= Conductivity)) + 
  geom_tile(color = "white",width = 1, height = 1)+
  scale_fill_viridis(discrete=FALSE) +
  theme_minimal() +
  labs(y = "Samples")+
  theme(legend.text = element_text(size = 12), 
         legend.key.size = unit(0.4, 'cm'), 
         axis.title = element_text(size = 16), 
         axis.text.x = element_blank(),
         axis.ticks.x = element_blank(),
         axis.text.y = element_text(size = 16), 
         plot.title = element_text(size = 20), 
         axis.title.x = element_blank(),
         axis.title.y = element_text(size = 16, face = "bold"), 
         legend.title = element_text(size = 16))+
  coord_fixed(ratio = 1)
```


```{r}
df_long <- df %>%
  pivot_longer(cols = c(pH, Moisture, Conductivity, Ash, Total_sugar, Colorimetry), # Añadir las otras columnas aquí
               names_to = "Parameter",
               values_to = "Value")
```

```{r}
# Graficar boxplot con jitter para todas las columnas en un solo gráfico
box_plot_phy <- ggplot(df_long, aes(x = Specie, y = Value, fill = Specie)) +
  geom_boxplot(width = 0.2) +
  geom_jitter(color="black", size=1, alpha=0.9) +
  scale_fill_manual(values = c("#b8860b", "#FFBF00")) +  # Personalizar colores para las especies
  facet_wrap(~Parameter, scales = "free_y") +  # Facetas para cada variable
  theme_ipsum() +
  theme_gray()+
  theme(legend.position = "right")+
  theme(strip.text = element_text(size = 14, face = "bold"),
    legend.text = element_text(size = 16), 
        axis.title = element_text(size = 20), 
        #axis.text.x = element_text(size = 14, face="italic", angle = 45, hjust = 1),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 16), 
        plot.title = element_text(size = 20), 
        axis.title.x = element_text(size = 16, face = "bold"),
        axis.title.y = element_text(size = 16, face = "bold"), 
        legend.title = element_text(size = 18))+
  xlab("")+
  labs(fill = "Specie")


box_plot_phy
```


```{r, eval=FALSE, include=FALSE}
ggsave(filename = "D:/Users/hayde/Documents/R_sites/honey_diversity/figures/boxplots.svg", plot = box_plot_phy, width = 10, height = 6, dpi = 300)
```


```{r, eval=FALSE}
#NO
ggplot(df_long, aes(x = Parameter, y = Value, fill = Specie)) +
  geom_boxplot(width = 0.2) +  # Hace los boxplots más delgados
  geom_jitter(color="black", size=1, alpha=0.9, width = 0.15) +  # Agrega dispersión
  
  scale_fill_manual(values = c("#b8860b", "#FFBF00")) +  # Personalizar colores para las especies

  # Facet en una sola fila sin espacios extras
  facet_grid(~ Parameter, scales = "free_y", space = "free_x") +

  theme_ipsum() +
  theme(
    legend.position = "bottom",  # Ubica la leyenda abajo
    legend.text = element_text(size = 16), 
    axis.title = element_text(size = 16), 
    axis.text.x = element_blank(),  # Eliminar etiquetas de los ejes
    axis.ticks.x = element_blank(), 
    axis.text.y = element_text(size = 16), 
    plot.title = element_text(size = 20), 
    axis.title.x = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 16, face = "bold"), 
    legend.title = element_text(size = 18)
  ) +
  
  xlab("") +
  labs(fill = "Specie")  # Título de la leyenda de colores

```
