---
title: 'ANI'
author:
 - Haydé Peruyero (haydeeperuyero@gmail.com)
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r, echo=FALSE, warning=FALSE}
library("phyloseq")
library("ggplot2")
library("RColorBrewer")
library("patchwork")
library("readr")
library("tidyverse")
library("grid")
library("gridExtra")
library("paletteer")
library("forcats")
library(viridis)
library(hrbrthemes)
```

```{r}
matriz_ani <- read.csv("D:/Users/hayde/Documents/R_sites/honey_diversity/results/ANI/matriz_ani.csv", stringsAsFactors = FALSE)


samples <- c("22_Melli.029", "45_Melli.020", "47_Melli.001", "41_Melli.001",
  "45_Melli.016", "40_Melli.029", "23_Scapto.001", "89_Scapto.001", "92_Scapto.002", "42_Melli.004", "89_Scapto.002", "51_Scapto.004", "92_Scapto.009", "90_Scapto.012", "46_Melli.022", 
  "A. jinshanensis subs. aerogenes", "A. jinshanensis strain HSLZ-75", "A. jinshanensis brasiliensis", "A. kunkeei")

matriz_ani <- matriz_ani[, -1]
rownames(matriz_ani) <- samples

colnames(matriz_ani) <- c("22_Melli.029", "45_Melli.020", "47_Melli.001", "41_Melli.001",
  "45_Melli.016", "40_Melli.029", "23_Scapto.001", "89_Scapto.001", "92_Scapto.002", "42_Melli.004", "89_Scapto.002", "51_Scapto.004", "92_Scapto.009", "90_Scapto.012", "46_Melli.022", 
  "A. jinshanensis subs. aerogenes", "A. jinshanensis strain HSLZ-75", "A. jinshanensis brasiliensis", "A. kunkeei")

```


```{r}
data <- as.matrix(matriz_ani)
```

```{r}
heatmap(data)
```





```{r}
df_ani <- read_delim("D:/Users/hayde/Documents/R_sites/honey_diversity/results/ANI/fastani.out.corredted", 
    delim = "\t", escape_double = FALSE, 
    col_names = FALSE, trim_ws = TRUE)

colnames(df_ani) <- c("query", "reference", "ani", "cbfm", "tqf")

df_ani$query <- recode(df_ani$query,
                      "Acetilactobacillus_jinshanensis_aerogenes_strain_Sichuan_bran_vinegar" = "A. jinshanensis subs. aerogenes",
                       "Acetilactobacillus_jinshanensis_strain_HSLZ-75" = "A. jinshanensis strain HSLZ-75",
                      "Acetilactobacillus_jinshanensis_brasiliensis" = "A. jinshanensis brasiliensis",
                      "Apilactobacillus_kunkeei" = "A. kunkeei"
                       )

df_ani$reference <- recode(df_ani$reference,
                      "Acetilactobacillus_jinshanensis_aerogenes_strain_Sichuan_bran_vinegar" = "A. jinshanensis subs. aerogenes",
                       "Acetilactobacillus_jinshanensis_strain_HSLZ-75" = "A. jinshanensis strain HSLZ-75",
                      "Acetilactobacillus_jinshanensis_brasiliensis" = "A. jinshanensis brasiliensis",
                      "Apilactobacillus_kunkeei" = "A. kunkeei"
                       )


niveles <- c("22_Melli.029", "45_Melli.020", "47_Melli.001", "41_Melli.001",
  "45_Melli.016", "40_Melli.029", "46_Melli.022",
  "23_Scapto.001", "89_Scapto.001", "92_Scapto.002", "42_Melli.004",
  "89_Scapto.002", "51_Scapto.004", "92_Scapto.009", "90_Scapto.012",
  "A. jinshanensis subs. aerogenes", "A. jinshanensis strain HSLZ-75", "A. jinshanensis brasiliensis", "A. kunkeei")

```

```{r}
df_ani$query <- factor(df_ani$query, levels = niveles)
df_ani$reference <- factor(df_ani$reference, levels = niveles)
```

```{r}
#Paso 1: Obtener los IDs únicos
ids_unicos <- unique(c(df_ani$query, df_ani$reference))

ids_unicos <- factor(ids_unicos, levels = niveles)

# Paso 2: Crear una matriz vacía con estos IDs
matriz_ani <- matrix(0, nrow = length(ids_unicos), ncol = length(ids_unicos),
                     dimnames = list(ids_unicos, ids_unicos))

# Paso 3: Llenar la matriz con los valores de `ani`
for (i in 1:nrow(df_ani)) {
  matriz_ani[df_ani$query[i], df_ani$reference[i]] <- df_ani$ani[i]
}


# Convertimos la matriz a un data frame largo
df_long <- as.data.frame(as.table(matriz_ani))

# Cambiar los nombres de las columnas
colnames(df_long) <- c("query", "reference", "ani")
```

```{r, echo=FALSE}
ggplot(df_ani, aes(x = reference, y = query, fill = ani)) + 
  geom_tile() +
  scale_fill_viridis(discrete = FALSE, limits = c(0, 100)) +  # Ajustar la escala de colores
  geom_text(aes(label = round(ani, 1)), color = "black", size = 3) +  # Agregar valores a las celdas
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90),  # Rotar etiquetas del eje x
        axis.text.y = element_text(size = 8),
        axis.title.x = element_text(size = 8),
        axis.title.y = element_text(size = 8),
        plot.title = element_text(size = 16)) +
  labs(title = "Heatmap con Valores", fill = "Valor de ani")
```

